"""Coding Agent trace adapter."""

from lumiagent.adapters.coding.conventions import (
    CODING_APPROVAL_DECISION,
    CODING_ARTIFACT_ACTION_EVIDENCE,
    CODING_ARTIFACT_SEMANTIC_EVIDENCE,
    CODING_ARTIFACT_WORKFLOW_CHECKS,
    CODING_ARTIFACT_WORKFLOW_FINDING,
    CODING_CODE_EDIT,
    CODING_CONTEXT_GATHERING,
    CODING_CONVENTIONS,
    CODING_DOMAIN,
    CODING_ERROR_OBSERVED,
    CODING_FAILURE_RECOVERY,
    CODING_FILE_READ,
    CODING_FILE_SEARCH,
    CODING_FINAL_RESPONSE,
    CODING_GIT_DIFF,
    CODING_PERMISSION_REQUEST,
    CODING_RESULT_INTERPRETATION,
    CODING_SHELL_COMMAND,
    CODING_TASK_UNDERSTANDING,
    CODING_TEST_RUN,
    CODING_USER_PROMPT,
    CODING_VERIFICATION,
    CODING_WORKFLOW_CHECK,
    coding_metadata,
)
from lumiagent.adapters.coding.events import (
    CodingActionEvidence,
    CodingSemanticEvidence,
    CodingWorkflowChecks,
    CodingWorkflowFinding,
    NormalizedCodingEvent,
)
from lumiagent.adapters.coding.normalizer import normalize_hook_event
from lumiagent.adapters.coding.validator import validate_coding_workflow
from lumiagent.adapters.coding.viewer import is_coding_trace, render_coding_trace_summary

__all__ = [
    "CODING_APPROVAL_DECISION",
    "CODING_ARTIFACT_ACTION_EVIDENCE",
    "CODING_ARTIFACT_SEMANTIC_EVIDENCE",
    "CODING_ARTIFACT_WORKFLOW_CHECKS",
    "CODING_ARTIFACT_WORKFLOW_FINDING",
    "CODING_CODE_EDIT",
    "CODING_CONTEXT_GATHERING",
    "CODING_CONVENTIONS",
    "CODING_DOMAIN",
    "CODING_ERROR_OBSERVED",
    "CODING_FAILURE_RECOVERY",
    "CODING_FILE_READ",
    "CODING_FILE_SEARCH",
    "CODING_FINAL_RESPONSE",
    "CODING_GIT_DIFF",
    "CODING_PERMISSION_REQUEST",
    "CODING_RESULT_INTERPRETATION",
    "CODING_SHELL_COMMAND",
    "CODING_TASK_UNDERSTANDING",
    "CODING_TEST_RUN",
    "CODING_USER_PROMPT",
    "CODING_VERIFICATION",
    "CODING_WORKFLOW_CHECK",
    "CodingActionEvidence",
    "CodingSemanticEvidence",
    "CodingWorkflowChecks",
    "CodingWorkflowFinding",
    "NormalizedCodingEvent",
    "coding_metadata",
    "is_coding_trace",
    "normalize_hook_event",
    "render_coding_trace_summary",
    "validate_coding_workflow",
]
